### ISSUE TITLE
Review Governance contract

### ISSUE THREAD

**Issue by ferittuncer** [kleros/kleros#104]

**Comment by mtsalenc** [comment]
In what branch and file is the code?

**Comment by mtsalenc** [comment]
https://docs.google.com/document/d/164K6zvfQ7TYG0LZD_uFnokkWeZ9Ovnc9vHIAv7MpN_c/edit

**Comment by satello** [comment]
https://docs.google.com/document/d/1Vwu8Q-11mKj7pirFGbyY3FUVd-cdO_RtnAmOjDymy-A/edit

**Comment by ferittuncer** [comment]
@satello The review document is not public.
