### ISSUE TITLE
Pre-Review KlerosLiquid

### ISSUE THREAD

**Issue by epiqueras** [kleros/kleros#113]
https://docs.google.com/document/d/16g3jwVbRLnWQkpPsmHI6LsHkGJ9f69PGLfzkiRlu5tE/edit?usp=sharing

**Comment by clesaege** [comment]
Review: https://docs.google.com/document/d/16g3jwVbRLnWQkpPsmHI6LsHkGJ9f69PGLfzkiRlu5tE/edit?usp=sharing

**Comment by unknownunknown1** [comment]
My review: https://docs.google.com/document/d/1cEeHn7WoCJHnz8scWZ1iahMduqZHDbioMusSROcvOHo/edit
Nothing serious found

**Comment by clesaege** [comment]
New review: https://docs.google.com/document/d/1FLmXWv-9gDYST958IN_dAYEWOkszCWh8BCTQlQRXQKE/edit#

**Comment by ferittuncer** [comment]
https://docs.google.com/document/d/1E6_lHNm78wYL38X9mcOBwqKG6nZCz2CBMympoZNIHAM/edit?usp=sharing

**Comment by clesaege** [comment]
Quick review (computer review of only modified functions): https://docs.google.com/document/d/1wEgl9bOOgE7sJyVjd_j3TYocBKczZLoq_iLfZ_NP9Ro/edit?usp=sharing

**Comment by unknownunknown1** [comment]
https://docs.google.com/document/d/1oXwpVlzrcTxR45Sd3_BEBUDIq0aoN3RShVvKHBLnX9Q/edit?usp=sharing

**Comment by n1c01a5** [comment]
https://docs.google.com/document/d/1lYE9WJ9Y62yAuuJlYU537-GUNFjypu4CQsD5cBoLV04/edit#heading=h.uw3g9px7u45v

**Comment by mtsalenc** [comment]
Closing this as the contract went through the audit.
