### ISSUE TITLE
Travis Ten Minutes Timeout Problem

### ISSUE THREAD

**Issue by ferittuncer** [kleros/kleros#131]
Travis times out if no output received within ten minutes.
Currently, coverage report command gets timed out because of this.

I tried to use the `--verbose` flag to make coverage command produce output more often (https://github.com/kleros/kleros/commit/0e8df689d15f2ff1b22abca05450c342a8516258) and tried `travis_wait` function to make Travis wait (https://github.com/kleros/kleros/commit/8a9533f7ea93c485c37cf3d88b5b4922541f4beb), but I couldn't succeed.

Related: https://docs.travis-ci.com/user/common-build-problems/

**Comment by cylim** [comment]
I didn't take a deep look into the implementation, from what I can see in the travis log https://travis-ci.org/kleros/kleros/builds/566338326#L376

The last command running is `yarn test` (which run `solidarity-coverage`), I assume that if you need to set `verbose` or `travis_wait`, should set it for the `yarn test` ?
