### ISSUE TITLE
Move All Proposals to IPFS

### ISSUE THREAD

**Issue by ferittuncer** [kleros/kleros#142]
Some of them are on GitHub right now.

**Comment by satello** [comment]
In addition to this we should refactor to use the format `/ipfs/...` for policies to be agnostic to the gateway. Currently policies on IPFS are using the ipfs.kleros.io prefix and it is causing error logs in Court

**Comment by clesaege** [comment]
That was done in the new contract https://etherscan.io/address/0xcf1f07713d5193fae5c1653c9f61953d048bece4#readContract
