### ISSUE TITLE
Review Comments in Contracts

### ISSUE THREAD

**Issue by ferittuncer** [kleros/kleros#143]
Someone reported that some links in comments are broken.

**Comment by pasDamola** [comment]
Hi @ferittuncer can i take this up? And what do i need to do. Would like to contribute

**Comment by ferittuncer** [comment]
Hi @pasDamola , outside contributions are welcome, so please go for it.

What needs to be done is to review each comment and check whether the information is still relevant. And if not, update it.

For example:
 - A broken link: Replace it with new one.
 - An explanation about how things work, but it's not true anymore: Update the explanation.

**Comment by hqrshguptq** [comment]
Hi @ferittuncer 
Was the issue resolved?

**Comment by ferittuncer** [comment]
Hi @hqrshguptq up for grabs.

**Comment by hqrshguptq** [comment]
Okay I will look into this please assign this. 
Moreover I have been a Frontend/React Developer of 2 years experience and saw a post somewhere regarding Dapp Internship by @clesaege. Do you have more info regarding this? 
I also want to contribute solve some issues on the Kleros Website Repo. Please suggest me or you can tag me on the issues which are currently open.. 
May I know on which tech-stack is the website built?

**Comment by hqrshguptq** [comment]
Okay @ferittuncer I will look into this please assign this.
Moreover I have been a Frontend/React Developer of 2 years experience and saw a post somewhere regarding Dapp Internship by @clesaege. Do you have more info regarding this?
I also want to contribute solve some issues on the Kleros Website Repo. Please suggest me or you can tag me on the issues which are currently open..
May I know on which tech-stack is the website built?

**Comment by clesaege** [comment]
Hi @hqrshguptq, you can contact me at @clesaege on telegram if you are interested by the internship.

**Comment by hqrshguptq** [comment]
Sure.

**Comment by hqrshguptq** [comment]
Hi @ferittuncer In addition to your suggestion on the task work. Where is the Repo where changes are to be done?
or How can I just find comments or if you may tell which contracts are herein talked about?

**Comment by hqrshguptq** [comment]
![Screenshot 2020-07-22 at 5 05 38 PM](https://user-images.githubusercontent.com/54597242/88172069-090b5e00-cc3e-11ea-9eeb-e3aedd02cbec.png)
Help me with this error! Same while using npm run build.

**Comment by hqrshguptq** [comment]
Hey @ferittuncer , any updates on this?

**Comment by hqrshguptq** [comment]
Hi @ferittuncer , where are these comments at?

**Comment by hqrshguptq** [comment]
Which links are being talked about in here? @ferittuncer

**Comment by ferittuncer** [comment]
I don't know which links are broken, unfortunately. @hqrshguptq

**Comment by hqrshguptq** [comment]
Yea, that's the case. Thanks.
