### ISSUE TITLE
Allow Parties to Forfeit

### ISSUE THREAD

**Issue by epiqueras** [kleros/kleros#29]
Only the party that raised the dispute is allowed to forfeit, and they must pay all the fees.

**Comment by clesaege** [comment]
Good idea. But it should be done at the arbitrable contract level, not the arbitrator one.

**Comment by epiqueras** [comment]
@clesaege But you need a way for the arbitrable contract to cancel the dispute on the arbitrator don't you?

**Comment by clesaege** [comment]
Well, it's not possible to cancel the dispute, because jurors have to vote, so there must be a token redistribution.

**Comment by epiqueras** [comment]
@clesaege I think this could cause issues.

Imagine a party forfeits after some jurors have already voted. Let's say the forfeiting party was actually correct in raising the dispute and it forfeited due to X invalid reasons. Assuming we had honest and capable jurors, they would have voted for the forfeiting party. Now, jurors who have not voted yet would vote for the party that did not forfeit because of the forfeit. You see how this could mess up incentives?

We would have to disable forfeiting as soon as one juror has voted. But even then, you run the risk of jurors not being up to date with evidence before voting.

I think it would be easier to cancel token redistribution.

What are your thoughts?

**Comment by clesaege** [comment]
I think we have to disable evidence submission after some period.
It seems that forfeiting messes up incentives. I think it's just better not to allow forfeiting. If some want to forfeit, they can wait for the ruling to be given and reverse it after if it was given in its favor.

**Comment by epiqueras** [comment]
@clesaege 
I think that if you allow disputes to be cancelled, (no PNK redistribution), the incentives are fine, but you do open a potential time grief.

I'll close this for now and make a new issue for the evidence submission disabling.
