### ISSUE TITLE
Double Lockfiles

### ISSUE THREAD

**Issue by kdembler** [kleros/kleros#31]
Currently, there are both `package-lock.json` from npm and `yarn.lock` from yarn lockfiles in repo.
The point of having a lockfile is so that anyone downloading the project will get the exactly same versions of dependencies that has been tested by developers. However, with two lockfiles from two different tools it might be easy to forget to update one of them during dependency update and get them out of sync.
So I guess it would be a good practice to decide on which one to use and stick with it.

**Comment by clesaege** [comment]
We can keep `package-lock.json`. Feel free to PR to remove one.
