### ISSUE TITLE
KlerosPOCCourt relies on unpublished kleros-interaction features

### ISSUE THREAD

**Issue by kdembler** [kleros/kleros#36]
https://github.com/kleros/kleros/blob/4e3b2062e50072cea9af72b863a138164c2bed3f/contracts/KlerosPOCCourt.sol#L34

`maxLocalAppeals` was added to `kleros-interaction` after latest release (0.0.14), so after installing all of Kleros dependencies, building contracts fails. So `kleros-interaction` needs to be released with new functionality and its version has to be bumped up in Kleros dependencies.

**Comment by clesaege** [comment]
Done
