### ISSUE TITLE
Prepare a way to upgrade

### ISSUE THREAD

**Issue by clesaege** [kleros/kleros#40]
We need to have the court ready to be upgraded.
We need to discuss about the best way to do so.
One way could be to:
-Put the new court as the parent one.
-Lower the maximum amount of appeals before we "jump the court" to 0.
-Lower the appeal fee to 0.

**Comment by epiqueras** [comment]
Also see
https://github.com/kleros/kleros-interaction/blob/master/contracts/standard/proxy/ArbitratorVersioningProxy.sol

**Comment by clesaege** [comment]
Yeah, so all contracts would go to the proxy even in the long term?

**Comment by epiqueras** [comment]
Yes

**Comment by clesaege** [comment]
Ok, let's take the proxy as a long term solution too.
