### ISSUE TITLE
Prepare for governance

### ISSUE THREAD

**Issue by clesaege** [kleros/kleros#41]
Prepare the court for governance.
To do so, we can put a court governor which will be able to modify court parameters and upgrade the court.
We may have it centralized first but can then put a governance smart contract to vote on those.

**Comment by luisfidelis** [comment]
Is there anyone working on? If there isn't, i would like to start.

**Comment by clesaege** [comment]
You can take it.

**Comment by ferittuncer** [comment]
Are you still working on this @luisfidelis ?

**Comment by clesaege** [comment]
I don't think so.

**Comment by clesaege** [comment]
Done
