### ISSUE TITLE
Handle Stakes Such That It Allows Parameter Changes

### ISSUE THREAD

**Issue by clesaege** [kleros/kleros#8]
Currently
https://github.com/kleros/kleros/blob/master/contracts/KlerosPOC.sol#L334
is verified because we can't change the parameters.
But with parameter changes it could be violated.
We need to handle the amount atStake in a dispute by jurors in way that does not assume the parameters don't move.

**Comment by ferittuncer** [comment]
Is this still relevant for Athena release?

**Comment by ferittuncer** [comment]
@clesaege

**Comment by epiqueras** [comment]
`atStake` is calculated from `minActivatedTokens` for which there is a setter. @clesaege
