### ISSUE TITLE
Use MinimeERC20 to prepare for voting

### ISSUE THREAD

**Issue by clesaege** [kleros/kleros#9]
For the PNK contract:
https://github.com/kleros/kleros/blob/master/contracts/PinakionPOC.sol

MinimeERC20:
https://github.com/kleros/kleros-interaction/blob/master/contracts/standard/arbitration/ArbitrableTokens/MiniMeTokenERC20.sol

**Comment by ernesto-usal** [comment]
The objetive is only to make PinakionPOC.sol work with MiniMETokenER20.sol, no?

**Comment by clesaege** [comment]
Yes.

**Comment by clesaege** [comment]
This can be done directly by using MinimeToken.
Deposit must be replaced by approveAndCall and receiveApproval.

**Comment by kdembler** [comment]
I'd like to work on this.
I agree there's no need for a specific PNK contract, as all needed functionality is already implemented in MiniMe, however, as far as I can see, there's no way for Truffle's test's contract abstraction to integrate with external contracts (from outside repo) and they need some reference for PNK.
How about providing fake implementation in `test/` just for testing purposes?

**Comment by clesaege** [comment]
@kdembler Hi, there is absolutely no problem using contracts from others repo. See https://github.com/kleros/kleros/blob/master/contracts/KlerosPOC.sol#L10 for example.

**Comment by kdembler** [comment]
@clesaege Hey, I'm aware you can import contracts from other repos in contracts.
What I meant is that if there's no need for PNK contract per se (it's removed from repo) then some reference will be needed for Truffle ([here](https://github.com/kleros/kleros/blob/b8abc2f2c0cc7ee1f625e8c7e22abbaf26584626/test/klerosPOC.js#L4)) to be able to include it in tests, as `artifacts.require()` is only able to include local files.

**Comment by kdembler** [comment]
Okay, nevermind, I didn't notice it can import contracts from npm packages :)

**Comment by kdembler** [comment]
I'm having second thoughts about not having PNK contract.
In that case, every call to deposit (i.e. `approveAndCall`) will need to include Kleros contract address as there will be no way to store it in MiniMe, so (I guess) user application making these calls will always need to know current address. Is that all right?
On the other hand, having PNK contract with current functionality (`setKleros` and `deposit` (to Kleros contract)) doesn't seem to have any drawbacks.
What do you think @clesaege?

**Comment by clesaege** [comment]
> In that case, every call to deposit (i.e. `approveAndCall`) will need to include Kleros contract address as there will be no way to store it in MiniMe, so (I guess) user application making these calls will always need to know current address. Is that all right?
Yeah, the UI can handle it. This may also simplify migrations.

A PNK contract with current functionalities have the advantage of saving a bit of gas with the `approveAndCall`, but the inconvenient of being custom implementation, while it could just use a well known and standardized one.
