### ISSUE TITLE
Fix KlerosPOC Tests

### ISSUE THREAD

**Issue by epiqueras** [kleros/kleros#92]

**Comment by hellwolf** [comment]
Hi, I fixed the issue at https://github.com/kleros/kleros/pull/98, please have a look.

Note: tests passed, but somehow build failed: https://travis-ci.org/kleros/kleros/builds/435367401?utm_source=github_status&utm_medium=notification

**Comment by hellwolf** [comment]
ah, that's because of those linter errors...

**Comment by hellwolf** [comment]
replaced with the new PR https://github.com/kleros/kleros/pull/99
