### ISSUE TITLE
Add PNK to MyCrypto and MyEtherWallet

### ISSUE THREAD

**Issue by clesaege** [kleros/kleros#94]
https://kb.myetherwallet.com/tokens/token-creators-add-your-token-to-myetherwallet.html
https://github.com/ethereum-lists/tokens/tree/master/tokens

**Comment by ferittuncer** [comment]
https://github.com/MyEtherWallet/ethereum-lists/pull/832

**Comment by ferittuncer** [comment]
Pull request merged.

**Comment by ferittuncer** [comment]
https://github.com/ethereum-lists/tokens/pull/146

**Comment by ferittuncer** [comment]
This one is merged too.

**Comment by ferittuncer** [comment]
I don't see PNK token in the dropdown list on MEW.

**Comment by ferittuncer** [comment]
✅  MyEtherWallet now shows PNK

**Comment by ferittuncer** [comment]
This is MyCrypto's list: https://github.com/MyCryptoHQ/MyCrypto/blob/develop/common/config/tokens/eth.json

Waiting for it to be updated.

**Comment by ferittuncer** [comment]
Still waiting...

**Comment by epiqueras** [comment]
Done.
